### ISSUE TITLE
Stopped working on mac os 10.13 beta High Sierra

### ISSUE THREAD

**Issue by tema-borisov** [0x6368/LIFred#5]
Workflow stopped working after updating to mac os 10.13 beta
Alfred ver: 3.4.1 [860]

Alfred debug log:
```
Starting debug for 'LIFred'

[2017-07-29 16:32:47][input.scriptfilter] Queuing argument ''
[2017-07-29 16:32:47][input.scriptfilter] Script with argument '(null)' finished
[2017-07-29 16:32:47][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- alfred (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./lifx_script_filter.rb:10:in `<main>'
```

**Comment by 0x6368** [comment]
Looks like this is an issue with Alfred. I will take a closer look, if this error still exists when High Sierra is officially released.

**Comment by eidermar** [comment]
Could you re-open this issue? I'm having the same problem as the OP with the release version of High Sierra.
